import {
  Soup,
  Candy,
  Flame,
  Snowflake,
  Sun,
  ScrollText,
  Leaf,
  Heart,
  Sofa,
  CookingPot,
  CakeSlice,
  Wind,
  Zap,
  Utensils,
  Coins,
  Stamp,
  Star,
  Feather,
  Megaphone,
  Home,
  Sparkles,
  Camera,
  TrendingUp,
  HelpCircle,
  LucideIcon,
} from "lucide-react";

const tagIconMap: Record<string, LucideIcon> = {
  Savory: Soup,
  Sweet: Candy,
  Spicy: Flame,
  Cold: Snowflake,
  Warm: Sun,
  Traditional: ScrollText,
  Fresh: Leaf,
  Healthy: Heart,
  Comfort: Sofa,
  Grilled: CookingPot,
  Indulgent: CakeSlice,
  Refreshing: Wind,
  Quick: Zap,
  Filling: Utensils,
  Cheap: Coins,
  Authentic: Stamp,
  Popular: Star,
  Light: Feather,
  Bold: Megaphone,
  Familiar: Home,
  Unique: Sparkles,
  Photogenic: Camera,
  Trending: TrendingUp,
};

export const getTagIcon = (tagName: string): LucideIcon => {
  return tagIconMap[tagName] || HelpCircle;
};