import {
  Soup,
  Candy,
  Flame,
  Snowflake,
  Sun,
  ScrollText,
  Leaf,
  Heart,
  Sofa,
  CookingPot,
  CakeSlice,
  Wind,
  Zap,
  Utensils,
  Coins,
  Stamp,
  Star,
  Feather,
  Megaphone,
  Home,
  Sparkles,
  Camera,
  TrendingUp,
  HelpCircle,
  LucideIcon,
} from "lucide-react";

const tagIconMap: Record<string, LucideIcon> = {
  Gurih: Soup,
  Manis: Candy,
  Pedas: Flame,
  Dingin: Snowflake,
  Hangat: Sun,
  Tradisional: ScrollText,
  Segar: Leaf,
  Sehat: Heart,
  Murah: Coins,
  Ringan: Feather,
  Kekinian: TrendingUp,
  Panas: Flame,
  // Unused tags from original map
  Comfort: Sofa,
  Grilled: CookingPot,
  Indulgent: CakeSlice,
  Refreshing: Wind,
  Quick: Zap,
  Filling: Utensils,
  Authentic: Stamp,
  Popular: Star,
  Bold: Megaphone,
  Familiar: Home,
  Unique: Sparkles,
  Photogenic: Camera,
  Trending: TrendingUp,
};

export const getTagIcon = (tagName: string): LucideIcon => {
  return tagIconMap[tagName] || HelpCircle;
};